In [20]:
import pandas as pd

# Converting the Phytozome GFF3 to a table of gene coordinates

In [22]:
df = pd.read_csv("Zmays_493_RefGen_V4.gene.gff3", sep="\t", header=None, skiprows=3, low_memory=False)
df.head()

,0,1,2,3,4,5,6,7,8
0,1,phytozomev12,gene,44289,49837,.,+,.,ID=Zm00001d027230.RefGen_V4;Name=Zm00001d027230
1,1,phytozomev12,mRNA,44289,49837,.,+,.,ID=Zm00001d027230_T001.RefGen_V4;Name=Zm00001d...
2,1,phytozomev12,five_prime_UTR,44289,44350,.,+,.,ID=Zm00001d027230_T001.RefGen_V4.five_prime_UT...
3,1,phytozomev12,CDS,44351,44947,.,+,0,ID=Zm00001d027230_T001.RefGen_V4.CDS.1;Parent=...
4,1,phytozomev12,CDS,45666,45803,.,+,0,ID=Zm00001d027230_T001.RefGen_V4.CDS.2;Parent=...

In [60]:
genes = df[df[2]=="gene"]

# Trying to avoid error message about copy of a slice from a DataFrame saved onto itself
#https://stackoverflow.com/questions/51344329/pandas-try-using-locrow-indexer-col-indexer-value-instead
pd.options.mode.chained_assignment = None

def gff_split(val):
    return val.split("=")[-1]

genes.iloc[:,8] = genes[8].apply(gff_split)
genes = genes.drop(columns=[1, 2, 5, 7], axis=1)
genes.columns = ["chr", "start", "end", "strand", "id"]
genes

        chr   start     end strand              id
0         1   44289   49837      +  Zm00001d027230
13        1   50877   55716      -  Zm00001d027231
98        1   92299   95134      -  Zm00001d027232
107       1  111655  118312      -  Zm00001d027233
125       1  118683  119739      -  Zm00001d027234
...      ..     ...     ...    ...             ...
1599646  Pt  105072  107369      -   GRMZM5G894515
1599650  Pt   88701   88910      -   GRMZM5G898442
1599653  Pt  133827  134036      +   GRMZM5G898466
1599656  Pt   24733   26784      +   GRMZM5G899366
1599659  Pt   83036   83803      +   GRMZM5G899836

[39498 rows x 5 columns]

IndexError: iloc cannot enlarge its target object

In [32]:
genes

          0             1     2       3       4  5  6  7               8
0         1  phytozomev12  gene   44289   49837  .  +  .  Zm00001d027230
13        1  phytozomev12  gene   50877   55716  .  -  .  Zm00001d027231
98        1  phytozomev12  gene   92299   95134  .  -  .  Zm00001d027232
107       1  phytozomev12  gene  111655  118312  .  -  .  Zm00001d027233
125       1  phytozomev12  gene  118683  119739  .  -  .  Zm00001d027234
...      ..           ...   ...     ...     ... .. .. ..             ...
1599646  Pt  phytozomev12  gene  105072  107369  .  -  .   GRMZM5G894515
1599650  Pt  phytozomev12  gene   88701   88910  .  -  .   GRMZM5G898442
1599653  Pt  phytozomev12  gene  133827  134036  .  +  .   GRMZM5G898466
1599656  Pt  phytozomev12  gene   24733   26784  .  +  .   GRMZM5G899366
1599659  Pt  phytozomev12  gene   83036   83803  .  +  .   GRMZM5G899836

[39498 rows x 9 columns]